name: Trigger auto deployment for zr-container-test

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/zr-container-test-AutoDeployTrigger-7b1f1415-b64b-4810-8de6-885c0aa18c7e.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ZRCONTAINERTEST_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ZRCONTAINERTEST_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ZRCONTAINERTEST_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: docker.io
          registryUsername: ${{ secrets.ZRCONTAINERTEST_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ZRCONTAINERTEST_REGISTRY_PASSWORD }}
          containerAppName: zr-container-test
          resourceGroup: zr-container-test
          imageToBuild: zr/zr-container-test:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


